DROP TABLE IF EXISTS pulls;
DROP TABLE IF EXISTS issue_labels;
DROP TABLE IF EXISTS labels;
DROP TABLE IF EXISTS issue_comments;
DROP TABLE IF EXISTS issues;
DROP TABLE IF EXISTS ssh_keys;
DROP TABLE IF EXISTS org_members;
DROP TABLE IF EXISTS orgs;
