// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package db

import (
	"context"
)

const countAllRepos = `-- name: CountAllRepos :one
SELECT COUNT(*) FROM repos
`

func (q *Queries) CountAllRepos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllRepos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllUsers = `-- name: CountAllUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUserByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const listAllReposWithOwner = `-- name: ListAllReposWithOwner :many
SELECT r.id, r.owner_id, r.name, r.description, r.visibility, r.created_at, r.updated_at,
       COALESCE(u.username, o.name) AS owner_name
FROM repos r
LEFT JOIN users u ON u.id = r.owner_id
LEFT JOIN orgs o ON o.id = r.owner_id
ORDER BY r.created_at DESC
`

type ListAllReposWithOwnerRow struct {
	ID          int64
	OwnerID     int64
	Name        string
	Description string
	Visibility  string
	CreatedAt   int64
	UpdatedAt   int64
	OwnerName   string
}

func (q *Queries) ListAllReposWithOwner(ctx context.Context) ([]ListAllReposWithOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllReposWithOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReposWithOwnerRow
	for rows.Next() {
		var i ListAllReposWithOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, username, email, password_hash, is_admin, created_at, updated_at FROM users ORDER BY created_at ASC
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
