// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: collaborators.sql

package db

import (
	"context"
)

const addCollaborator = `-- name: AddCollaborator :exec
INSERT INTO collaborators (repo_id, user_id, created_at) VALUES (?, ?, ?)
`

type AddCollaboratorParams struct {
	RepoID    int64
	UserID    int64
	CreatedAt int64
}

func (q *Queries) AddCollaborator(ctx context.Context, arg AddCollaboratorParams) error {
	_, err := q.db.ExecContext(ctx, addCollaborator, arg.RepoID, arg.UserID, arg.CreatedAt)
	return err
}

const isCollaborator = `-- name: IsCollaborator :one
SELECT COUNT(*) FROM collaborators WHERE repo_id = ? AND user_id = ?
`

type IsCollaboratorParams struct {
	RepoID int64
	UserID int64
}

func (q *Queries) IsCollaborator(ctx context.Context, arg IsCollaboratorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isCollaborator, arg.RepoID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCollaborators = `-- name: ListCollaborators :many
SELECT u.id, u.username, u.email, u.password_hash, u.is_admin, u.created_at, u.updated_at FROM collaborators c
JOIN users u ON u.id = c.user_id
WHERE c.repo_id = ?
`

func (q *Queries) ListCollaborators(ctx context.Context, repoID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listCollaborators, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleReposForUser = `-- name: ListVisibleReposForUser :many
SELECT r.* FROM repos r
LEFT JOIN collaborators c ON c.repo_id = r.id AND c.user_id = ?
WHERE r.visibility = 'public'
   OR r.owner_id = ?
   OR c.user
`

type ListVisibleReposForUserParams struct {
	UserID  int64
	OwnerID int64
}

// 用户可见的仓库：自己的 + public + 协作的r.id, r.owner_id, r.name, r.description, r.visibility, r.created_at, r.updated_atorg 可见性 M5 补组织成员查询）
func (q *Queries) ListVisibleReposForUser(ctx context.Context, arg ListVisibleReposForUserParams) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listVisibleReposForUser, arg.UserID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollaborator = `-- name: RemoveCollaborator :exec
DELETE FROM collaborators WHERE repo_id = ? AND user_id = ?
`

type RemoveCollaboratorParams struct {
	RepoID int64
	UserID int64
}

func (q *Queries) RemoveCollaborator(ctx context.Context, arg RemoveCollaboratorParams) error {
	_, err := q.db.ExecContext(ctx, removeCollaborator, arg.RepoID, arg.UserID)
	return err
}
