// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: issues.sql

package db

import (
	"context"
	"database/sql"
)

const addLabel = `-- name: AddLabel :exec
INSERT INTO issue_labels (issue_id, label_id) VALUES (?, ?)
`

type AddLabelParams struct {
	IssueID int64
	LabelID int64
}

func (q *Queries) AddLabel(ctx context.Context, arg AddLabelParams) error {
	_, err := q.db.ExecContext(ctx, addLabel, arg.IssueID, arg.LabelID)
	return err
}

const countComments = `-- name: CountComments :one
SELECT COUNT(*) FROM issue_comments WHERE issue_id = ?
`

func (q *Queries) CountComments(ctx context.Context, issueID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countComments, issueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO issue_comments (issue_id, author_id, body, created_at)
VALUES (?, ?, ?, ?) RETURNING id, issue_id, author_id, body, created_at
`

type CreateCommentParams struct {
	IssueID   int64
	AuthorID  int64
	Body      string
	CreatedAt int64
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (IssueComment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.IssueID,
		arg.AuthorID,
		arg.Body,
		arg.CreatedAt,
	)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (repo_id, number, author_id, title, body, is_pull, closed, assignee_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, 0, ?, ?, ?) RETURNING id, repo_id, number, author_id, title, body, is_pull, closed, assignee_id, created_at, updated_at
`

type CreateIssueParams struct {
	RepoID     int64
	Number     int64
	AuthorID   int64
	Title      string
	Body       string
	IsPull     int64
	AssigneeID sql.NullInt64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, createIssue,
		arg.RepoID,
		arg.Number,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.IsPull,
		arg.AssigneeID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Number,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.IsPull,
		&i.Closed,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (repo_id, name, color) VALUES (?, ?, ?) RETURNING id, repo_id, name, color
`

type CreateLabelParams struct {
	RepoID int64
	Name   string
	Color  string
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, createLabel, arg.RepoID, arg.Name, arg.Color)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const getIssue = `-- name: GetIssue :one
SELECT id, repo_id, number, author_id, title, body, is_pull, closed, assignee_id, created_at, updated_at FROM issues WHERE repo_id = ? AND number = ?
`

type GetIssueParams struct {
	RepoID int64
	Number int64
}

func (q *Queries) GetIssue(ctx context.Context, arg GetIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssue, arg.RepoID, arg.Number)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Number,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.IsPull,
		&i.Closed,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, repo_id, number, author_id, title, body, is_pull, closed, assignee_id, created_at, updated_at FROM issues WHERE id = ?
`

func (q *Queries) GetIssueByID(ctx context.Context, id int64) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Number,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.IsPull,
		&i.Closed,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLabelByName = `-- name: GetLabelByName :one
SELECT id, repo_id, name, color FROM labels WHERE repo_id = ? AND name = ?
`

type GetLabelByNameParams struct {
	RepoID int64
	Name   string
}

func (q *Queries) GetLabelByName(ctx context.Context, arg GetLabelByNameParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabelByName, arg.RepoID, arg.Name)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT id, issue_id, author_id, body, created_at FROM issue_comments WHERE issue_id = ? ORDER BY created_at
`

func (q *Queries) ListComments(ctx context.Context, issueID int64) ([]IssueComment, error) {
	rows, err := q.db.QueryContext(ctx, listComments, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueComment
	for rows.Next() {
		var i IssueComment
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueLabels = `-- name: ListIssueLabels :many
SELECT l.id, l.repo_id, l.name, l.color FROM issue_labels il JOIN labels l ON l.id = il.label_id WHERE il.issue_id = ?
`

func (q *Queries) ListIssueLabels(ctx context.Context, issueID int64) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listIssueLabels, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssues = `-- name: ListIssues :many
SELECT id, repo_id, number, author_id, title, body, is_pull, closed, assignee_id, created_at, updated_at FROM issues WHERE repo_id = ?1 AND is_pull = ?2
ORDER BY created_at DESC LIMIT 100
`

type ListIssuesParams struct {
	RepoID int64
	IsPull int64
}

func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listIssues, arg.RepoID, arg.IsPull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Number,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.IsPull,
			&i.Closed,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByState = `-- name: ListIssuesByState :many
SELECT id, repo_id, number, author_id, title, body, is_pull, closed, assignee_id, created_at, updated_at FROM issues WHERE repo_id = ?1 AND is_pull = ?2 AND closed = ?3
ORDER BY created_at DESC LIMIT 100
`

type ListIssuesByStateParams struct {
	RepoID int64
	IsPull int64
	Closed int64
}

func (q *Queries) ListIssuesByState(ctx context.Context, arg ListIssuesByStateParams) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesByState, arg.RepoID, arg.IsPull, arg.Closed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Number,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.IsPull,
			&i.Closed,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many
SELECT id, repo_id, name, color FROM labels WHERE repo_id = ?
`

func (q *Queries) ListLabels(ctx context.Context, repoID int64) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabels, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextIssueNumber = `-- name: NextIssueNumber :one
SELECT COALESCE(MAX(number), 0) + 1 AS n FROM issues WHERE repo_id = ?
`

func (q *Queries) NextIssueNumber(ctx context.Context, repoID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextIssueNumber, repoID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const removeLabel = `-- name: RemoveLabel :exec
DELETE FROM issue_labels WHERE issue_id = ? AND label_id = ?
`

type RemoveLabelParams struct {
	IssueID int64
	LabelID int64
}

func (q *Queries) RemoveLabel(ctx context.Context, arg RemoveLabelParams) error {
	_, err := q.db.ExecContext(ctx, removeLabel, arg.IssueID, arg.LabelID)
	return err
}

const updateIssueAssignee = `-- name: UpdateIssueAssignee :exec
UPDATE issues SET assignee_id = ?, updated_at = ? WHERE id = ?
`

type UpdateIssueAssigneeParams struct {
	AssigneeID sql.NullInt64
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) UpdateIssueAssignee(ctx context.Context, arg UpdateIssueAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueAssignee, arg.AssigneeID, arg.UpdatedAt, arg.ID)
	return err
}

const updateIssueState = `-- name: UpdateIssueState :exec
UPDATE issues SET closed = ?, updated_at = ? WHERE id = ?
`

type UpdateIssueStateParams struct {
	Closed    int64
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdateIssueState(ctx context.Context, arg UpdateIssueStateParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueState, arg.Closed, arg.UpdatedAt, arg.ID)
	return err
}

const updateIssueTitleBody = `-- name: UpdateIssueTitleBody :exec
UPDATE issues SET title = ?, body = ?, updated_at = ? WHERE id = ?
`

type UpdateIssueTitleBodyParams struct {
	Title     string
	Body      string
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdateIssueTitleBody(ctx context.Context, arg UpdateIssueTitleBodyParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueTitleBody,
		arg.Title,
		arg.Body,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
