// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Collaborator struct {
	RepoID    int64
	UserID    int64
	CreatedAt int64
}

type Issue struct {
	ID         int64
	RepoID     int64
	Number     int64
	AuthorID   int64
	Title      string
	Body       string
	IsPull     int64
	Closed     int64
	AssigneeID sql.NullInt64
	CreatedAt  int64
	UpdatedAt  int64
}

type IssueComment struct {
	ID        int64
	IssueID   int64
	AuthorID  int64
	Body      string
	CreatedAt int64
}

type IssueLabel struct {
	IssueID int64
	LabelID int64
}

type Label struct {
	ID     int64
	RepoID int64
	Name   string
	Color  string
}

type Org struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   int64
}

type OrgMember struct {
	OrgID     int64
	UserID    int64
	Role      string
	CreatedAt int64
}

type Pat struct {
	ID         int64
	UserID     int64
	Name       string
	TokenHash  string
	CreatedAt  int64
	LastUsedAt sql.NullInt64
	Scope      string
	ExpiresAt  sql.NullInt64
}

type Pull struct {
	IssueID     int64
	RepoID      int64
	HeadRepoID  int64
	HeadBranch  string
	BaseBranch  string
	Merged      int64
	MergeCommit sql.NullString
}

type Repo struct {
	ID          int64
	OwnerID     int64
	Name        string
	Description string
	Visibility  string
	CreatedAt   int64
	UpdatedAt   int64
}

type Session struct {
	ID        string
	UserID    int64
	CsrfToken string
	ExpiresAt int64
	CreatedAt int64
}

type SshKey struct {
	ID          int64
	UserID      int64
	Name        string
	Fingerprint string
	PublicKey   string
	CreatedAt   int64
}

type TotpRecoveryCode struct {
	ID       int64
	UserID   int64
	CodeHash string
	Used     int64
}

type TotpUsed struct {
	UserID int64
	Window int64
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	IsAdmin      int64
	CreatedAt    int64
	UpdatedAt    int64
	TotpSecret   string
	TotpEnabled  int64
}
