// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Session struct {
	ID        string
	UserID    int64
	CsrfToken string
	ExpiresAt int64
	CreatedAt int64
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	IsAdmin      int64
	CreatedAt    int64
	UpdatedAt    int64
}
