// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orgs.sql

package db

import (
	"context"
)

const addOrgMember = `-- name: AddOrgMember :exec
INSERT INTO org_members (org_id, user_id, role, created_at) VALUES (?, ?, ?, ?)
`

type AddOrgMemberParams struct {
	OrgID     int64
	UserID    int64
	Role      string
	CreatedAt int64
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error {
	_, err := q.db.ExecContext(ctx, addOrgMember,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const countOrgByID = `-- name: CountOrgByID :one
SELECT COUNT(*) FROM orgs WHERE id = ?
`

func (q *Queries) CountOrgByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrgByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgMembers = `-- name: CountOrgMembers :one
SELECT COUNT(*) FROM org_members WHERE org_id = ?
`

func (q *Queries) CountOrgMembers(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrgMembers, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgsOfRepo = `-- name: CountOrgsOfRepo :one
SELECT COUNT(*) FROM orgs WHERE id = ?
`

func (q *Queries) CountOrgsOfRepo(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrgsOfRepo, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (name, description, created_at) VALUES (?, ?, ?) RETURNING id, name, description, created_at
`

type CreateOrgParams struct {
	Name        string
	Description string
	CreatedAt   int64
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRowContext(ctx, createOrg, arg.Name, arg.Description, arg.CreatedAt)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, description, created_at FROM orgs WHERE id = ?
`

func (q *Queries) GetOrgByID(ctx context.Context, id int64) (Org, error) {
	row := q.db.QueryRowContext(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgByName = `-- name: GetOrgByName :one
SELECT id, name, description, created_at FROM orgs WHERE name = ?
`

func (q *Queries) GetOrgByName(ctx context.Context, name string) (Org, error) {
	row := q.db.QueryRowContext(ctx, getOrgByName, name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT org_id, user_id, role, created_at FROM org_members WHERE org_id = ? AND user_id = ?
`

type GetOrgMemberParams struct {
	OrgID  int64
	UserID int64
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRowContext(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const isOrgMember = `-- name: IsOrgMember :one
SELECT COUNT(*) FROM org_members om
JOIN orgs o ON o.id = om.org_id
WHERE o.name = ?1 AND om.user_id = ?2
`

type IsOrgMemberParams struct {
	Name   string
	UserID int64
}

func (q *Queries) IsOrgMember(ctx context.Context, arg IsOrgMemberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isOrgMember, arg.Name, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isOrgMemberByOrgID = `-- name: IsOrgMemberByOrgID :one
SELECT COUNT(*) FROM org_members WHERE org_id = ? AND user_id = ?
`

type IsOrgMemberByOrgIDParams struct {
	OrgID  int64
	UserID int64
}

func (q *Queries) IsOrgMemberByOrgID(ctx context.Context, arg IsOrgMemberByOrgIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isOrgMemberByOrgID, arg.OrgID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listOrgMembersWithUsers = `-- name: ListOrgMembersWithUsers :many
SELECT u.id, u.username, u.email, u.password_hash, u.is_admin, u.created_at, u.updated_at,
       om.role AS member_role
FROM org_members om
JOIN users u ON u.id = om.user_id
WHERE om.org_id = ?
ORDER BY om.created_at
`

type ListOrgMembersWithUsersRow struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	IsAdmin      int64
	CreatedAt    int64
	UpdatedAt    int64
	MemberRole   string
}

func (q *Queries) ListOrgMembersWithUsers(ctx context.Context, orgID int64) ([]ListOrgMembersWithUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgMembersWithUsers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgMembersWithUsersRow
	for rows.Next() {
		var i ListOrgMembersWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgRepos = `-- name: ListOrgRepos :many
SELECT r.id, r.owner_id, r.name, r.description, r.visibility, r.created_at, r.updated_at FROM repos r JOIN orgs o ON r.owner_id = o.id WHERE o.name = ?1
`

func (q *Queries) ListOrgRepos(ctx context.Context, name string) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listOrgRepos, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
