// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pats.sql

package db

import (
	"context"
	"database/sql"
)

const createPAT = `-- name: CreatePAT :one
INSERT INTO pats (user_id, name, token_hash, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, name, token_hash, created_at, last_used_at, scope, expires_at
`

type CreatePATParams struct {
	UserID    int64
	Name      string
	TokenHash string
	CreatedAt int64
}

func (q *Queries) CreatePAT(ctx context.Context, arg CreatePATParams) (Pat, error) {
	row := q.db.QueryRowContext(ctx, createPAT,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
	)
	var i Pat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Scope,
		&i.ExpiresAt,
	)
	return i, err
}

const createScopedPAT = `-- name: CreateScopedPAT :one
INSERT INTO pats (user_id, name, token_hash, scope, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, user_id, name, token_hash, created_at, last_used_at, scope, expires_at
`

type CreateScopedPATParams struct {
	UserID    int64
	Name      string
	TokenHash string
	Scope     string
	CreatedAt int64
	ExpiresAt sql.NullInt64
}

func (q *Queries) CreateScopedPAT(ctx context.Context, arg CreateScopedPATParams) (Pat, error) {
	row := q.db.QueryRowContext(ctx, createScopedPAT,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Scope,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Pat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Scope,
		&i.ExpiresAt,
	)
	return i, err
}

const deletePAT = `-- name: DeletePAT :exec
DELETE FROM pats WHERE id = ? AND user_id = ?
`

type DeletePATParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeletePAT(ctx context.Context, arg DeletePATParams) error {
	_, err := q.db.ExecContext(ctx, deletePAT, arg.ID, arg.UserID)
	return err
}

const getPATByHash = `-- name: GetPATByHash :one
SELECT id, user_id, name, token_hash, created_at, last_used_at, scope, expires_at FROM pats WHERE token_hash = ?
`

func (q *Queries) GetPATByHash(ctx context.Context, tokenHash string) (Pat, error) {
	row := q.db.QueryRowContext(ctx, getPATByHash, tokenHash)
	var i Pat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Scope,
		&i.ExpiresAt,
	)
	return i, err
}

const listPATsByUser = `-- name: ListPATsByUser :many
SELECT id, user_id, name, token_hash, created_at, last_used_at FROM pats WHERE user_id = ?
`

type ListPATsByUserRow struct {
	ID         int64
	UserID     int64
	Name       string
	TokenHash  string
	CreatedAt  int64
	LastUsedAt sql.NullInt64
}

func (q *Queries) ListPATsByUser(ctx context.Context, userID int64) ([]ListPATsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPATsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPATsByUserRow
	for rows.Next() {
		var i ListPATsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPATsFull = `-- name: ListPATsFull :many
SELECT id, user_id, name, token_hash, created_at, last_used_at, scope, expires_at FROM pats WHERE user_id = ?
`

func (q *Queries) ListPATsFull(ctx context.Context, userID int64) ([]Pat, error) {
	rows, err := q.db.QueryContext(ctx, listPATsFull, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pat
	for rows.Next() {
		var i Pat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Scope,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPAT = `-- name: TouchPAT :exec
UPDATE pats SET last_used_at = ? WHERE id = ?
`

type TouchPATParams struct {
	LastUsedAt sql.NullInt64
	ID         int64
}

func (q *Queries) TouchPAT(ctx context.Context, arg TouchPATParams) error {
	_, err := q.db.ExecContext(ctx, touchPAT, arg.LastUsedAt, arg.ID)
	return err
}
