// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pulls.sql

package db

import (
	"context"
	"database/sql"
)

const createPull = `-- name: CreatePull :exec
INSERT INTO pulls (issue_id, repo_id, head_repo_id, head_branch, base_branch, merged, merge_commit)
VALUES (?, ?, ?, ?, ?, 0, '')
`

type CreatePullParams struct {
	IssueID    int64
	RepoID     int64
	HeadRepoID int64
	HeadBranch string
	BaseBranch string
}

func (q *Queries) CreatePull(ctx context.Context, arg CreatePullParams) error {
	_, err := q.db.ExecContext(ctx, createPull,
		arg.IssueID,
		arg.RepoID,
		arg.HeadRepoID,
		arg.HeadBranch,
		arg.BaseBranch,
	)
	return err
}

const getOpenPullByBranches = `-- name: GetOpenPullByBranches :one
SELECT p.issue_id, p.repo_id, p.head_repo_id, p.head_branch, p.base_branch, p.merged, p.merge_commit FROM pulls p
JOIN issues i ON i.id = p.issue_id
WHERE p.repo_id = ?1 AND p.head_branch = ?2 AND p.base_branch = ?3 AND i.closed = 0
`

type GetOpenPullByBranchesParams struct {
	RepoID     int64
	HeadBranch string
	BaseBranch string
}

func (q *Queries) GetOpenPullByBranches(ctx context.Context, arg GetOpenPullByBranchesParams) (Pull, error) {
	row := q.db.QueryRowContext(ctx, getOpenPullByBranches, arg.RepoID, arg.HeadBranch, arg.BaseBranch)
	var i Pull
	err := row.Scan(
		&i.IssueID,
		&i.RepoID,
		&i.HeadRepoID,
		&i.HeadBranch,
		&i.BaseBranch,
		&i.Merged,
		&i.MergeCommit,
	)
	return i, err
}

const getPullByIssue = `-- name: GetPullByIssue :one
SELECT issue_id, repo_id, head_repo_id, head_branch, base_branch, merged, merge_commit FROM pulls WHERE issue_id = ?
`

func (q *Queries) GetPullByIssue(ctx context.Context, issueID int64) (Pull, error) {
	row := q.db.QueryRowContext(ctx, getPullByIssue, issueID)
	var i Pull
	err := row.Scan(
		&i.IssueID,
		&i.RepoID,
		&i.HeadRepoID,
		&i.HeadBranch,
		&i.BaseBranch,
		&i.Merged,
		&i.MergeCommit,
	)
	return i, err
}

const listPullsWithIssue = `-- name: ListPullsWithIssue :many
SELECT i.id, i.repo_id, i.number, i.author_id, i.title, i.body, i.is_pull, i.closed,
       i.assignee_id, i.created_at, i.updated_at,
       p.head_branch, p.base_branch, p.merged, p.merge_commit
FROM pulls p
JOIN issues i ON i.id = p.issue_id
WHERE p.repo_id = ?
ORDER BY i.created_at DESC LIMIT 100
`

type ListPullsWithIssueRow struct {
	ID          int64
	RepoID      int64
	Number      int64
	AuthorID    int64
	Title       string
	Body        string
	IsPull      int64
	Closed      int64
	AssigneeID  sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
	HeadBranch  string
	BaseBranch  string
	Merged      int64
	MergeCommit sql.NullString
}

func (q *Queries) ListPullsWithIssue(ctx context.Context, repoID int64) ([]ListPullsWithIssueRow, error) {
	rows, err := q.db.QueryContext(ctx, listPullsWithIssue, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPullsWithIssueRow
	for rows.Next() {
		var i ListPullsWithIssueRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Number,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.IsPull,
			&i.Closed,
			&i.AssigneeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HeadBranch,
			&i.BaseBranch,
			&i.Merged,
			&i.MergeCommit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergePull = `-- name: MergePull :exec
UPDATE pulls SET merged = 1, merge_commit = ? WHERE issue_id = ?
`

type MergePullParams struct {
	MergeCommit sql.NullString
	IssueID     int64
}

func (q *Queries) MergePull(ctx context.Context, arg MergePullParams) error {
	_, err := q.db.ExecContext(ctx, mergePull, arg.MergeCommit, arg.IssueID)
	return err
}
