// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: repos.sql

package db

import (
	"context"
	"database/sql"
)

const countReposByOwner = `-- name: CountReposByOwner :one
SELECT COUNT(*) FROM repos WHERE owner_id = ?
`

func (q *Queries) CountReposByOwner(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReposByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (owner_id, name, description, visibility, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, owner_id, name, description, visibility, created_at, updated_at
`

type CreateRepoParams struct {
	OwnerID     int64
	Name        string
	Description string
	Visibility  string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, createRepo,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos WHERE id = ?
`

func (q *Queries) DeleteRepo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRepo, id)
	return err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, owner_id, name, description, visibility, created_at, updated_at FROM repos WHERE id = ?
`

func (q *Queries) GetRepoByID(ctx context.Context, id int64) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepoByID, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByOrgAndName = `-- name: GetRepoByOrgAndName :one
SELECT r.id, r.owner_id, r.name, r.description, r.visibility, r.created_at, r.updated_at FROM repos r
JOIN orgs o ON o.id = r.owner_id
WHERE o.name = ? AND r.name = ?
`

type GetRepoByOrgAndNameParams struct {
	Name   string
	Name_2 string
}

func (q *Queries) GetRepoByOrgAndName(ctx context.Context, arg GetRepoByOrgAndNameParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepoByOrgAndName, arg.Name, arg.Name_2)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByOwnerAndName = `-- name: GetRepoByOwnerAndName :one
SELECT r.id, r.owner_id, r.name, r.description, r.visibility, r.created_at, r.updated_at FROM repos r
JOIN users u ON u.id = r.owner_id
WHERE u.username = ? AND r.name = ?
`

type GetRepoByOwnerAndNameParams struct {
	Username string
	Name     string
}

func (q *Queries) GetRepoByOwnerAndName(ctx context.Context, arg GetRepoByOwnerAndNameParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepoByOwnerAndName, arg.Username, arg.Name)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicRepos = `-- name: ListPublicRepos :many
SELECT id, owner_id, name, description, visibility, created_at, updated_at FROM repos WHERE visibility = 'public'
ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListPublicRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listPublicRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByOwner = `-- name: ListReposByOwner :many
SELECT r.id, r.owner_id, r.name, r.description, r.visibility, r.created_at, r.updated_at FROM repos r
JOIN users u ON u.id = r.owner_id
WHERE u.username = ?
ORDER BY r.created_at DESC
`

func (q *Queries) ListReposByOwner(ctx context.Context, username string) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposByOwner, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRepos = `-- name: SearchRepos :many
SELECT id, owner_id, name, description, visibility, created_at, updated_at FROM repos
WHERE (name LIKE '%' || ? || '%' OR description LIKE '%' || ? || '%')
ORDER BY created_at DESC LIMIT 50
`

type SearchReposParams struct {
	Column1 sql.NullString
	Column2 sql.NullString
}

func (q *Queries) SearchRepos(ctx context.Context, arg SearchReposParams) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, searchRepos, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepo = `-- name: UpdateRepo :exec
UPDATE repos SET description = ?, visibility = ?, updated_at = ? WHERE id = ?
`

type UpdateRepoParams struct {
	Description string
	Visibility  string
	UpdatedAt   int64
	ID          int64
}

func (q *Queries) UpdateRepo(ctx context.Context, arg UpdateRepoParams) error {
	_, err := q.db.ExecContext(ctx, updateRepo,
		arg.Description,
		arg.Visibility,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
