// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sshkeys.sql

package db

import (
	"context"
)

const createSSHKey = `-- name: CreateSSHKey :one
INSERT INTO ssh_keys (user_id, name, fingerprint, public_key, created_at)
VALUES (?, ?, ?, ?, ?) RETURNING id, user_id, name, fingerprint, public_key, created_at
`

type CreateSSHKeyParams struct {
	UserID      int64
	Name        string
	Fingerprint string
	PublicKey   string
	CreatedAt   int64
}

func (q *Queries) CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRowContext(ctx, createSSHKey,
		arg.UserID,
		arg.Name,
		arg.Fingerprint,
		arg.PublicKey,
		arg.CreatedAt,
	)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Fingerprint,
		&i.PublicKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSSHKey = `-- name: DeleteSSHKey :exec
DELETE FROM ssh_keys WHERE id = ? AND user_id = ?
`

type DeleteSSHKeyParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteSSHKey(ctx context.Context, arg DeleteSSHKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteSSHKey, arg.ID, arg.UserID)
	return err
}

const getSSHKeyByFingerprint = `-- name: GetSSHKeyByFingerprint :one
SELECT id, user_id, name, fingerprint, public_key, created_at FROM ssh_keys WHERE fingerprint = ?
`

func (q *Queries) GetSSHKeyByFingerprint(ctx context.Context, fingerprint string) (SshKey, error) {
	row := q.db.QueryRowContext(ctx, getSSHKeyByFingerprint, fingerprint)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Fingerprint,
		&i.PublicKey,
		&i.CreatedAt,
	)
	return i, err
}

const listSSHKeysByUser = `-- name: ListSSHKeysByUser :many
SELECT id, user_id, name, fingerprint, public_key, created_at FROM ssh_keys WHERE user_id = ?
`

func (q *Queries) ListSSHKeysByUser(ctx context.Context, userID int64) ([]SshKey, error) {
	rows, err := q.db.QueryContext(ctx, listSSHKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SshKey
	for rows.Next() {
		var i SshKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Fingerprint,
			&i.PublicKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
