// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: totp.sql

package db

import (
	"context"
)

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO totp_recovery_codes (user_id, code_hash, used) VALUES (?, ?, 0)
`

type CreateRecoveryCodeParams struct {
	UserID   int64
	CodeHash string
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, createRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM totp_recovery_codes WHERE user_id = ?
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodes, userID)
	return err
}

const listRecoveryCodes = `-- name: ListRecoveryCodes :many
SELECT id, user_id, code_hash, used FROM totp_recovery_codes WHERE user_id = ? AND used = 0
`

func (q *Queries) ListRecoveryCodes(ctx context.Context, userID int64) ([]TotpRecoveryCode, error) {
	rows, err := q.db.QueryContext(ctx, listRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotpRecoveryCode
	for rows.Next() {
		var i TotpRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.Used,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTOTPUsed = `-- name: MarkTOTPUsed :exec
INSERT OR IGNORE INTO totp_used (user_id, "window") VALUES (?, ?)
`

type MarkTOTPUsedParams struct {
	UserID int64
	Window int64
}

func (q *Queries) MarkTOTPUsed(ctx context.Context, arg MarkTOTPUsedParams) error {
	_, err := q.db.ExecContext(ctx, markTOTPUsed, arg.UserID, arg.Window)
	return err
}

const useRecoveryCode = `-- name: UseRecoveryCode :exec
UPDATE totp_recovery_codes SET used = 1 WHERE id = ?
`

func (q *Queries) UseRecoveryCode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, useRecoveryCode, id)
	return err
}
